Repository ember-truncate/ember-truncate, pull requests merged in 2021-06, with the labels that each got.

#370 Adds release-it for publishing
  .eslintcache
  CHANGELOG.md
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#376 Converting to github actions
  .eslintignore
  .github/workflows/ci-build.yml
  .lint-todo/215d693fb10e8b672bdcbdcaa9fa4a324d83bc95/09b3461c.json
  .lint-todo/3ad45ca37ecc03ecb2d1a438a756440431b8d1f6/34bb96f3.json
  .lint-todo/902723da80114bea6912916d98a30e2c28650af0/25d48526.json
  .lint-todo/902723da80114bea6912916d98a30e2c28650af0/85acd18f.json
  .lint-todo/902723da80114bea6912916d98a30e2c28650af0/b56f4e39.json
  .lint-todo/902723da80114bea6912916d98a30e2c28650af0/d52be4da.json
  .lint-todo/902723da80114bea6912916d98a30e2c28650af0/feb49d2e.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/0e0519fd.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/12dd5c54.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/1309a7e8.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/256caf58.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/2a5b7f96.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/2a5d0e99.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/3927d88c.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/3ce06c93.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/46536262.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/4ae9a93e.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/5b937adb.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/640e3251.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/687de002.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/6ce01d5c.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/6f06ab1b.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/73ecf25e.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/953f44e2.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/ab5827c8.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/b584ca7b.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/ce61aa4d.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/cef9d672.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/d0419538.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/d8e79a7e.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/e01fe9e4.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/e3b671b4.json
  .lint-todo/e41469ac3cc8c186796c1e2d86f8fb9949a9f5d2/fc42eba1.json
  .travis.yml
  config/ember-try.js
Labels: internal

#377 Remove ember-lifeline and re-roll lockfile
  .bowerrc
  .jshintrc
  package.json
  tests/.jshintrc
  yarn.lock
Labels: dependencies

#378 Ember Modules & Angle Brackets Codemods
  .lint-todo/3ad45ca37ecc03ecb2d1a438a756440431b8d1f6/34bb96f3.json
  addon/components/truncate-multiline.js
  tests/dummy/app/templates/application.hbs
  tests/helpers/module-for-acceptance.js
  tests/integration/components/truncate-multiline-test.js
Labels: enhancement
